import type { WellnessEvent } from "@/lib/types";

export const events: WellnessEvent[] = [
  {
    id: "beginner-breathwork-circle",
    title: "Beginner Breathwork Circle",
    description:
      "A gentle introduction to breathwork in a small, welcoming group. Learn two grounding practices you can use in everyday life.",
    category: "Mindfulness",
    date: "Sat, Jul 12",
    time: "10:30 AM–11:30 AM",
    location: "TMU area",
    format: "In-person",
    price: 0,
    host: "Maya at Open Room",
    hostInitials: "MO",
    sponsored: false,
    community: true,
    size: "Small group",
    comfort: "Solo-friendly",
    beginnerFriendly: true,
    accessibility: "Step-free entrance, chairs available, low-scent space.",
    audience: "Anyone curious about breathwork, especially first-timers.",
    expectations:
      "We begin with a short welcome, practise seated breathing together, and close with an optional reflection. Sharing is always optional.",
    maxAttendees: 14,
    spotsLeft: 6,
    bookingUrl: "#",
    accent: "sage",
  },
  {
    id: "sunday-wellness-walk",
    title: "Sunday Morning Wellness Walk",
    description:
      "An unhurried waterfront walk with pauses for conversation, fresh air, and a warm drink at the end.",
    category: "Outdoor",
    date: "Sun, Jul 13",
    time: "9:30 AM–11:00 AM",
    location: "Toronto Waterfront",
    format: "In-person",
    price: 0,
    host: "Toronto Slow Club",
    hostInitials: "TS",
    sponsored: false,
    community: true,
    size: "Medium group",
    comfort: "Social",
    beginnerFriendly: true,
    accessibility: "Flat paved route; washrooms available at the meeting point.",
    audience: "Newcomers, students, and anyone looking for low-pressure connection.",
    expectations:
      "A 3 km walk at a conversational pace. Come alone or with a friend; a host will welcome new walkers.",
    maxAttendees: 28,
    spotsLeft: 12,
    bookingUrl: "#",
    accent: "blue",
  },
  {
    id: "journaling-for-burnout",
    title: "Journaling for Burnout",
    description:
      "A quiet online workshop with simple prompts for noticing what drains you and what helps you recover.",
    category: "Creative",
    date: "Tue, Jul 15",
    time: "7:00 PM–8:15 PM",
    location: "Online",
    format: "Online",
    price: 12,
    host: "Nia Writes Well",
    hostInitials: "NW",
    sponsored: false,
    community: false,
    size: "Small group",
    comfort: "Solo-friendly",
    beginnerFriendly: true,
    accessibility: "Live captions, prompts shared in chat, camera optional.",
    audience: "Students and professionals feeling stretched or creatively stuck.",
    expectations:
      "Three guided writing rounds, short pauses, and an optional closing discussion. You never have to read your work aloud.",
    maxAttendees: 18,
    spotsLeft: 8,
    bookingUrl: "#",
    accent: "lilac",
  },
  {
    id: "gentle-yoga-for-students",
    title: "Gentle Yoga for Students",
    description:
      "A slower-paced class focused on mobility, rest, and feeling comfortable in your body. Mats are provided.",
    category: "Movement",
    date: "Wed, Jul 16",
    time: "5:30 PM–6:30 PM",
    location: "Downtown Toronto",
    format: "In-person",
    price: 8,
    host: "Common Ground Yoga",
    hostInitials: "CG",
    sponsored: false,
    community: false,
    size: "Medium group",
    comfort: "Solo-friendly",
    beginnerFriendly: true,
    accessibility: "Elevator access, all-gender washroom, pose alternatives offered.",
    audience: "Students of all movement levels. No yoga experience needed.",
    expectations:
      "Comfortable floor and standing movement, with plenty of rest. Wear anything you can move in.",
    maxAttendees: 20,
    spotsLeft: 5,
    bookingUrl: "#",
    accent: "sand",
  },
  {
    id: "creative-reset-collage",
    title: "Creative Reset: Collage & Conversation",
    description:
      "Make something with your hands and meet a few kind people. Supplies, tea, and gentle prompts are included.",
    category: "Creative",
    date: "Thu, Jul 17",
    time: "6:00 PM–8:00 PM",
    location: "Allan Gardens",
    format: "In-person",
    price: 15,
    host: "Neighbourhood Table",
    hostInitials: "NT",
    sponsored: false,
    community: true,
    size: "Small group",
    comfort: "Small group",
    beginnerFriendly: true,
    accessibility: "Step-free room, quiet corner, materials suitable for varied dexterity.",
    audience: "Anyone who wants a creative evening without pressure to be an artist.",
    expectations:
      "A host-led welcome, open collage time, and optional table conversation. Materials are provided.",
    maxAttendees: 16,
    spotsLeft: 4,
    bookingUrl: "#",
    accent: "peach",
  },
  {
    id: "mindful-movement-park",
    title: "Mindful Movement at the Park",
    description:
      "Light mobility, standing stretches, and a short grounding practice beneath the trees.",
    category: "Outdoor",
    date: "Sat, Jul 19",
    time: "11:00 AM–12:00 PM",
    location: "Trinity Bellwoods",
    format: "In-person",
    price: 0,
    host: "Move Kindly TO",
    hostInitials: "MK",
    sponsored: false,
    community: true,
    size: "Medium group",
    comfort: "Social",
    beginnerFriendly: true,
    accessibility: "Mostly level grass; seated alternatives and visual instructions.",
    audience: "All bodies and experience levels.",
    expectations:
      "Low-impact movement with no equipment. Bring water and a layer for the weather.",
    maxAttendees: 24,
    spotsLeft: 14,
    bookingUrl: "#",
    accent: "sage",
  },
  {
    id: "calm-studio-intro",
    title: "Calm Studio Intro Class",
    description:
      "Try a restorative studio class combining gentle stretching, breath, and a guided rest.",
    category: "Movement",
    date: "Sun, Jul 20",
    time: "4:00 PM–5:15 PM",
    location: "Community studio",
    format: "In-person",
    price: 10,
    host: "Calm Studio Toronto",
    hostInitials: "CS",
    sponsored: true,
    sponsorName: "Calm Studio Toronto",
    community: false,
    size: "Small group",
    comfort: "Solo-friendly",
    beginnerFriendly: true,
    accessibility: "Step-free studio, low lighting, scent-free request supported.",
    audience: "New studio visitors looking for a calm, beginner-friendly class.",
    expectations:
      "A staff welcome, 45 minutes of supported movement, and 15 minutes to ask questions or look around.",
    maxAttendees: 14,
    spotsLeft: 7,
    bookingUrl: "#",
    accent: "blue",
  },
  {
    id: "plant-forward-kitchen",
    title: "Easy Plant-Forward Kitchen",
    description:
      "Cook an affordable weeknight meal together and leave with a flexible recipe you can make your own.",
    category: "Food & Nutrition",
    date: "Mon, Jul 21",
    time: "6:30 PM–8:00 PM",
    location: "TMU area",
    format: "In-person",
    price: 24,
    host: "Sprout Community Kitchen",
    hostInitials: "SK",
    sponsored: true,
    sponsorName: "Sprout Community Kitchen",
    community: false,
    size: "Small group",
    comfort: "Small group",
    beginnerFriendly: true,
    accessibility: "Seated prep station, allergen list available, support person welcome.",
    audience: "Beginner cooks, students, and anyone wanting a more social dinner routine.",
    expectations:
      "Small teams prepare one shared meal with a facilitator. Ingredients and containers are included.",
    maxAttendees: 12,
    spotsLeft: 3,
    bookingUrl: "#",
    accent: "sand",
  },
  {
    id: "newcomer-potluck-walk",
    title: "Newcomer Potluck Walk",
    description:
      "A neighbourhood stroll followed by a casual shared snack. Bring something small only if you can.",
    category: "Social",
    date: "Sat, Jul 26",
    time: "2:00 PM–4:00 PM",
    location: "Allan Gardens",
    format: "In-person",
    price: 0,
    host: "New Here Toronto",
    hostInitials: "NH",
    sponsored: false,
    community: true,
    size: "Medium group",
    comfort: "Social",
    beginnerFriendly: true,
    accessibility: "Paved route, nearby washrooms, no food contribution required.",
    audience: "People new to Toronto and locals who want to make the city feel friendlier.",
    expectations:
      "A hosted introduction, a 30-minute walk in pairs, then snacks and open conversation in the park.",
    maxAttendees: 25,
    spotsLeft: 10,
    bookingUrl: "#",
    accent: "peach",
  },
];

export const featuredEvents = events.slice(0, 3);
export const partnerEvents = events.filter((event) => event.sponsored);
export const communityEvents = events.filter((event) => event.community);

export const getEventById = (id: string) =>
  events.find((event) => event.id === id);
